from django.db import models

# Create your model here.
class Features(models.Model):
    vol_outscan = models.FloatField(max_length=20)
    vol_del = models.FloatField(max_length=20)
    ppd_Vol = models.FloatField(max_length=20)
    ppd_Delv_Vol = models.FloatField(max_length=20)
    cod_Vol = models.FloatField(max_length=20)
    cod_Delv_Vol = models.FloatField(max_length=20)
    RTS_Vol = models.FloatField(max_length=20)
    RTS_Delv_Vol = models.FloatField(max_length=20)
    EDS_Vol = models.FloatField(max_length=20)
    EDS_Pickup_Completed = models.FloatField(max_length=20)
    RVP_Pickup_Vol = models.FloatField(max_length=20)
    RVP_Pickup_Completed = models.FloatField(max_length=20)
    RVP_Outscan_Vol = models.FloatField(max_length=20)
    RVP_Delv_Vol = models.FloatField(max_length=20)
    weight = models.FloatField(max_length=20)
    Amazon = models.FloatField(max_length=20)
    Flipkart = models.FloatField(max_length=20)
    Club_Factory = models.FloatField(max_length=20)
    Paytm = models.FloatField(max_length=20)
    Myntra = models.FloatField(max_length=20)
    Snap_Deal = models.FloatField(max_length=20)
    others = models.FloatField(max_length=20)
    FE_Type = models.FloatField(max_length=20)
    Voucher_Number = models.FloatField(max_length=20)
    Total_Km = models.FloatField(max_length=20)
    fuel_exp = models.FloatField(max_length=20)
    Fuel_Expenses_Reimbursed = models.FloatField(max_length=20)
