# Generated by Django 2.2 on 2019-04-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='lastname',
            new_name='lname',
        ),
    ]
